version: "3"
services:
  USLM-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: USLM-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=USLM
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=buy_first
  USLM-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: USLM-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=USLM
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=sell_first
  JOUT-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: JOUT-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=JOUT
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=buy_first
  JOUT-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: JOUT-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=JOUT
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=sell_first
  OFLX-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: OFLX-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=OFLX
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=buy_first
  OFLX-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: OFLX-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=OFLX
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=sell_first
  WINA-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: WINA-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=WINA
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=buy_first
  WINA-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: WINA-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=WINA
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=sell_first
  BFC-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: BFC-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=BFC
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=buy_first
  BFC-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: BFC-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=BFC
    - KINGFISHER_CLIENT_ID=
    - KINGFISHER_STRATEGY=sell_first
version: "3"
services:
  USLM-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: USLM-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=USLM
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=buy_first
  USLM-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: USLM-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=USLM
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=sell_first
  JOUT-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: JOUT-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=JOUT
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=buy_first
  JOUT-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: JOUT-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=JOUT
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=sell_first
  OFLX-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: OFLX-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=OFLX
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=buy_first
  OFLX-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: OFLX-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=OFLX
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=sell_first
  WINA-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: WINA-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=WINA
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=buy_first
  WINA-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: WINA-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=WINA
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=sell_first
  BFC-buy_first-2021-04-08
    image: 1e61ffc591cb
    container_name: BFC-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=BFC
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=buy_first
  BFC-sell_first-2021-04-08
    image: 1e61ffc591cb
    container_name: BFC-buy_first-2021-04-08
    network_mode: host
    environment:
    - KINGFISHER_TARGET=BFC
    - KINGFISHER_CLIENT_ID=${CLIENT_ID}
    - KINGFISHER_STRATEGY=sell_first
